version: '3.7'
services:
  elasticsearch:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
      args:
        VERSION: 7.15.2
    container_name: elasticsearch
    environment:
      - node.name=single-node
      - cluster.name=es-cluster-1
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    container_name: docker-kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    # Elasticsearch Start Dependency
    depends_on:
      - elasticsearch
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge