version: '3'
services:
  spring-app:
    container_name: jewelry-spring
    image: "${{ secrets.DOCKER_REPO }}/jewelry:latest"
    ports:
      - "8080:8080"
  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
    depends_on:
      - jewelry-spring